<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Bhaskar-pc" failures="1" tests="1" name="Test" time="0.568" errors="0" timestamp="2025-08-21T10:05:08 IST">
  <testcase classname="Wipro.TC0012_TestNG" name="f" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3">
      <![CDATA[java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
at Wipro.TC0012_TestNG.dp(TC0012_TestNG.java:73)
... 25 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- f -->
</testsuite> <!-- Test -->
